# Copyright (c) 2026 kogeler
# SPDX-License-Identifier: MIT

"""Regression tests for the exact GitHub dependency-submission snapshot."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
SNAPSHOT_SCRIPT = ROOT / ".github" / "scripts" / "dependency_snapshot.py"
LOCKS = ("requirements.txt", "requirements-dev.txt", "requirements-lint.txt")


def _run_snapshot(root: Path, output: Path) -> subprocess.CompletedProcess[str]:
    """Run the production snapshot helper against a selected repository root."""
    return subprocess.run(
        [
            sys.executable,
            str(SNAPSHOT_SCRIPT),
            "--root",
            str(root),
            "--output",
            str(output),
        ],
        check=False,
        capture_output=True,
        text=True,
    )


def _copy_inputs(destination: Path) -> None:
    """Copy only the five authoritative dependency inputs used by the helper."""
    (destination / "tools/lint").mkdir(parents=True)
    shutil.copy2(ROOT / "pyproject.toml", destination / "pyproject.toml")
    shutil.copy2(ROOT / "tools/lint/pyproject.toml", destination / "tools/lint/pyproject.toml")
    for lock in LOCKS:
        shutil.copy2(ROOT / lock, destination / lock)


def test_snapshot_contains_all_three_exact_lock_graphs(tmp_path: Path) -> None:
    """Runtime, development, and Ruff locks are separate complete manifests."""
    output = tmp_path / "snapshot.json"
    result = _run_snapshot(ROOT, output)

    assert result.returncode == 0, result.stderr
    payload = json.loads(output.read_text(encoding="utf-8"))
    assert set(payload) == {"manifests"}
    assert set(payload["manifests"]) == set(LOCKS)

    runtime = payload["manifests"]["requirements.txt"]
    development = payload["manifests"]["requirements-dev.txt"]
    lint = payload["manifests"]["requirements-lint.txt"]
    for name, manifest in payload["manifests"].items():
        assert manifest["name"] == name
        assert manifest["file"] == {"source_location": name}
        assert manifest["resolved"]

    assert runtime["resolved"]["xmltodict"] == {
        "package_url": "pkg:pypi/xmltodict@1.0.4",
        "relationship": "direct",
        "scope": "runtime",
    }
    assert runtime["resolved"]["certifi"]["relationship"] == "indirect"
    assert {item["scope"] for item in runtime["resolved"].values()} == {"runtime"}
    assert development["resolved"]["homeassistant"]["relationship"] == "direct"
    assert development["resolved"]["certifi"]["relationship"] == "indirect"
    assert {item["scope"] for item in development["resolved"].values()} == {"development"}
    assert lint["resolved"] == {
        "ruff": {
            "package_url": "pkg:pypi/ruff@0.16.1",
            "relationship": "direct",
            "scope": "development",
        }
    }


def test_snapshot_rejects_unrecognized_lock_content(tmp_path: Path) -> None:
    """New resolver syntax cannot silently disappear from the submitted graph."""
    _copy_inputs(tmp_path)
    runtime = tmp_path / "requirements.txt"
    runtime.write_text(runtime.read_text(encoding="utf-8") + "--index-url example.invalid\n")

    result = _run_snapshot(tmp_path, tmp_path / "snapshot.json")

    assert result.returncode == 1
    assert "unsupported lock entry" in result.stderr


def test_snapshot_rejects_missing_direct_dependency(tmp_path: Path) -> None:
    """A direct PEP 621 dependency must occur at its exact version in the lock."""
    _copy_inputs(tmp_path)
    project = tmp_path / "pyproject.toml"
    project.write_text(
        project.read_text(encoding="utf-8").replace(
            '  "xmltodict==1.0.4",', '  "missing-package==1.0.0",'
        ),
        encoding="utf-8",
    )

    result = _run_snapshot(tmp_path, tmp_path / "snapshot.json")

    assert result.returncode == 1
    assert "direct dependencies missing from lock: missing-package" in result.stderr


def test_snapshot_rejects_hashless_pin(tmp_path: Path) -> None:
    """The API inventory cannot be generated from a non-hash lock."""
    _copy_inputs(tmp_path)
    lint = tmp_path / "requirements-lint.txt"
    lint.write_text(
        "# This file is autogenerated by pip-compile\nruff==0.16.1 \\\n    # via test\n",
        encoding="utf-8",
    )

    result = _run_snapshot(tmp_path, tmp_path / "snapshot.json")

    assert result.returncode == 1
    assert "ruff==0.16.1 has no SHA-256 hash" in result.stderr
