# Copyright (c) 2026 kogeler
# SPDX-License-Identifier: MIT

"""Repository policy for dependency environments and confined execution."""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).parents[1]
LOCK_PIN = re.compile(r"^([A-Za-z0-9._-]+)==([^\s\\]+)")
MAKE_TARGET = re.compile(r"^([a-z][a-z0-9-]*):", re.MULTILINE)


def _read_lock(path: Path) -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = LOCK_PIN.match(line)
        if match:
            name = canonicalize_name(match.group(1))
            assert name not in pins, f"duplicate lock pin: {path.name}: {name}"
            pins[name] = match.group(2)
    return pins


def _exact(requirement: str) -> tuple[str, str]:
    parsed = Requirement(requirement)
    specifiers = list(parsed.specifier)
    assert parsed.url is None
    assert parsed.marker is None
    assert len(specifiers) == 1 and specifiers[0].operator == "==", requirement
    return canonicalize_name(parsed.name), specifiers[0].version


def test_pep621_owns_every_direct_python_dependency() -> None:
    """Runtime, development, and host Ruff inputs have one explicit owner each."""
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    lint_project = tomllib.loads((ROOT / "tools/lint/pyproject.toml").read_text(encoding="utf-8"))[
        "project"
    ]
    manifest = json.loads(
        (ROOT / "custom_components/fmi/manifest.json").read_text(encoding="utf-8")
    )

    runtime = dict(_exact(item) for item in project["dependencies"])
    manifest_runtime = dict(_exact(item) for item in manifest["requirements"])
    assert runtime == manifest_runtime
    assert runtime == {
        "fmi-weather-client": "1.0.0",
        "xmltodict": "1.0.4",
    }

    development = dict(_exact(item) for item in project["optional-dependencies"]["dev"])
    assert set(project["optional-dependencies"]) == {"dev"}
    assert development == {
        "bandit": "1.9.4",
        "homeassistant": "2026.8.1",
        "mypy": "2.3.0",
        "packaging": "26.3",
        "pip-audit": "2.10.1",
        "pip-licenses": "5.5.5",
        "pylint": "4.0.6",
        "pytest": "9.0.3",
        "pytest-asyncio": "1.4.0",
        "pytest-cov": "7.1.0",
        "pytest-homeassistant-custom-component": "0.13.355",
        "pytest-socket": "0.8.0",
        "pytest-xdist": "3.8.0",
    }
    assert lint_project["dependencies"] == ["ruff==0.16.1"]


def test_exactly_three_generated_hash_locks_are_split_by_audience() -> None:
    """The runtime, toolbox, and Ruff environments cannot silently merge."""
    lock_paths = sorted(ROOT.glob("requirements*.txt"))
    assert [path.name for path in lock_paths] == [
        "requirements-dev.txt",
        "requirements-lint.txt",
        "requirements.txt",
    ]
    assert not (ROOT / "requirements").exists()
    assert not list(ROOT.rglob("*.in"))

    runtime = _read_lock(ROOT / "requirements.txt")
    development = _read_lock(ROOT / "requirements-dev.txt")
    lint = _read_lock(ROOT / "requirements-lint.txt")
    assert set(runtime) <= set(development)
    assert all(development[name] == version for name, version in runtime.items())
    assert "ruff" not in development
    assert "pip-tools" not in development
    assert lint == {"ruff": "0.16.1"}

    for path in lock_paths:
        content = path.read_text(encoding="utf-8")
        assert "autogenerated by pip-compile" in content
        assert "--hash=sha256:" in content
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    assert "chmod 0644 $(RUNTIME_LOCK) $(DEVELOPMENT_LOCK) $(LINT_LOCK)" in makefile


def test_resolver_bootstrap_is_the_only_inline_install_set() -> None:
    """The self-hosting resolver exception remains exact, complete, and wheel-only."""
    containerfile = (ROOT / "containers/toolbox/Containerfile").read_text(encoding="utf-8")
    lock_stage = containerfile.split("FROM base AS lock", maxsplit=1)[1].split(
        "FROM base AS dev", maxsplit=1
    )[0]
    assert "--only-binary=:all:" in lock_stage
    assert "--require-hashes" not in lock_stage
    for requirement in (
        "pip==26.2.1",
        "setuptools==84.0.0",
        "pip-tools==7.6.1",
        "build==1.5.0",
        "click==8.4.2",
        "packaging==26.3",
        "pyproject-hooks==1.2.0",
        "wheel==0.48.0",
    ):
        assert requirement in lock_stage

    dev_stage = containerfile.split("FROM base AS dev", maxsplit=1)[1]
    assert "--require-hashes" in dev_stage
    assert "requirements-dev.txt" in dev_stage
    assert "python -m pip check" in dev_stage
    assert "==" not in dev_stage
    assert "COPY ." not in containerfile

    for path in [ROOT / "Makefile", *sorted((ROOT / ".github").rglob("*.py"))]:
        for line in path.read_text(encoding="utf-8").splitlines():
            if "pip install" in line or '"pip", "install"' in line:
                assert "==" not in line, path


def test_toolbox_policy_streams_source_and_enforces_confinement() -> None:
    """Project-aware containers never receive the host checkout as a mount."""
    policy = (ROOT / "make/container.mk").read_text(encoding="utf-8")
    entrypoint = (ROOT / "containers/toolbox/entrypoint.sh").read_text(encoding="utf-8")
    for flag in (
        "--network=none",
        "--userns=auto:size=2048",
        "--security-opt=no-new-privileges",
        "--cap-drop=ALL",
        "--read-only",
        "--unsetenv-all",
        "--pids-limit=1024",
    ):
        assert flag in policy
    assert "--volume" not in policy
    assert "--mount=type=bind" not in policy
    assert "git ls-files --cached --others --exclude-standard" in policy
    assert '[[ -e "$$path" || -L "$$path" ]]' in policy
    for proof in ("id -u", "CapEff", "NoNewPrivs", "Seccomp"):
        assert proof in entrypoint
    assert "BOX_EXPORT_ON_SUCCESS" in entrypoint


def test_every_pytest_entry_point_uses_automatic_xdist_workers() -> None:
    """No maintained offline, live, network, or compatibility suite is serial."""
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    compatibility = (ROOT / ".github/scripts/compatibility.py").read_text(encoding="utf-8")
    repository_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in [
            ROOT / "Makefile",
            ROOT / ".github/scripts/compatibility.py",
            *ROOT.glob(".github/workflows/*.yml"),
        ]
    )
    assert "PYTEST_WORKERS ?= auto" in makefile
    assert "-n $(PYTEST_WORKERS) --dist=worksteal" in makefile
    assert '"-n",\n                "auto",' in compatibility
    assert '"--dist=worksteal"' in compatibility
    assert "-n 0" not in repository_text
    assert "PYTEST_WORKERS ?= 0" not in repository_text


def test_make_target_surface_has_no_legacy_or_duplicate_execution_path() -> None:
    """Keep one explicit target graph and serialize its shared state boundaries."""
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    container = (ROOT / "make/container.mk").read_text(encoding="utf-8")
    targets = set(MAKE_TARGET.findall(makefile + container))
    assert targets == {
        "audit",
        "audit-raw",
        "bandit",
        "check",
        "ci",
        "clean",
        "clean-containers",
        "compatibility-prerelease",
        "compatibility-stable",
        "confinement-test",
        "coverage-report",
        "dependency-snapshot",
        "dev-build",
        "doctor",
        "format",
        "format-check",
        "freeze-check",
        "help",
        "image-key",
        "image-load",
        "image-load-resolver",
        "image-load-toolbox",
        "image-save",
        "image-save-resolver",
        "image-save-toolbox",
        "images",
        "licenses",
        "lint",
        "lint-venv",
        "live",
        "lock",
        "lock-image",
        "outdated",
        "refresh-dependencies",
        "release-notes",
        "shellcheck",
        "syntax",
        "test-fast",
        "test-full",
        "test-network-block",
        "toolbox-image",
        "type-check",
        "validate",
        "validate-actions",
        "validate-hacs",
        "validate-hassfest",
        "validate-local",
        "validator-images",
        "version-check",
        "version-sync",
    }
    assert ".NOTPARALLEL:" in makefile
    assert "freeze-check validate \\\n\tdependency-snapshot" in makefile
    assert "check: lint type-check bandit syntax shellcheck test-full" in makefile
    assert "check: format-check" not in makefile
    assert "development-seed" not in makefile


def test_make_failure_exports_and_coverage_reports_are_unambiguous() -> None:
    """Failed atomic commands emit valid empty tar and partial coverage is not publishable."""
    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    container = (ROOT / "make/container.mk").read_text(encoding="utf-8")
    entrypoint = (ROOT / "containers/toolbox/entrypoint.sh").read_text(encoding="utf-8")
    assert "BOX_EXPORT_ON_SUCCESS" in entrypoint
    assert entrypoint.count("tar --create --file=- --files-from=/dev/null") == 2
    assert "-s $(ARTIFACTS)/coverage.xml" in makefile
    assert "-s $(ARTIFACTS)/$(COVERAGE_REPORT)" in makefile
    assert "-s $(ARTIFACTS)/$(COVERAGE_TOTAL)" in makefile
    assert "rm -rf" not in makefile
    assert "rm -rf" not in container
